<a href="https://colab.research.google.com/github/yih789/Data-Analysis-and-Image-Processing/blob/master/Numpy%EC%9D%98_%EA%B8%B0%EB%B3%B8_%EC%82%AC%EC%9A%A9%EB%B2%95.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

 * Python의 **Numpy** 라이브러리는 **List**와 상호 변환이 가능하다.

In [0]:
import numpy as np

array = np.array([1, 2, 3])
print(array.size) # 배열의 크기
print(array.dtype) # 배열 원소의 타입
print(array[2])

3
int64
3


* Python의 **Numpy** 라이브러리는 다양한 형태의 배열을 초기화 할 수 있다.

In [0]:
import numpy as np

# 0부터 3까지의 배열 만들기
array1 = np.arange(4)
print(array1, '\n')

# 0으로 초기화
array2 = np.zeros((4, 4), dtype = float)
print(array2, '\n')

# 1로 초기화
array3 = np.ones((3, 3), dtype = str)
print(array3, '\n')

# 0부터 9까지 랜덤하게 초기화 된 배열 만들기
array4 = np.random.randint(0, 10, (3, 3))
print(array4, '\n')

# 평균이 0이고 표준편차가 1인 표준 정규를 띄는 배열
array5 = np.random.normal(0, 1, (3, 3))
print(array5, '\n')

[0 1 2 3] 

[[0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]] 

[['1' '1' '1']
 ['1' '1' '1']
 ['1' '1' '1']] 

[[2 5 1]
 [6 1 9]
 [2 5 9]] 

[[-0.19033629 -0.32910098 -0.60161492]
 [-0.2633235   0.76436126  0.48371205]
 [ 0.79392552  0.43640973 -0.62936043]] 



**Numpy**는 다양한 형태로 **합치기**가 가능

In [0]:
import numpy as np

array1 = np.array([1, 2, 3])
array2 = np.array([4, 5, 6])
array3 = np.concatenate([array1, array2])

print(array3.shape)
print(array3)

(6,)
[1 2 3 4 5 6]


**Numpy**를 위 아래로 합칠 수 있다.

In [0]:
import numpy as np

array1 = np.arange(4).reshape(1, 4)
array2 = np.arange(8).reshape(2, 4)
array3 = np.concatenate([array1, array2], axis = 0)

print(array3.shape)
print(array3)

(3, 4)
[[0 1 2 3]
 [0 1 2 3]
 [4 5 6 7]]


**Numpy**의 형태를 변경할 수 있다.
* reshape()

In [0]:
import numpy as np

array1 = np.array([1, 2, 3, 4])
array2 = array1.reshape((2, 2))
print(array2.shape)


(2, 2)


**Numpy**의 형태를 **나누기**할 수 있다.

In [0]:
import numpy as np

array = np.arange(8).reshape(2, 4)
left, right = np.split(array, [2], axis = 1)

print(array, '\n')
print(left, '\n')
print(right, '\n')

[[0 1 2 3]
 [4 5 6 7]] 

[[0 1]
 [4 5]] 

[[2 3]
 [6 7]] 

