<a href="https://colab.research.google.com/github/yih789/Data-Analysis-and-Image-Processing/blob/master/Numpy%EC%97%B0%EC%82%B0%EA%B3%BC_%ED%95%A8%EC%88%98.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

* **Numpy** 라이브러리는 상수 연산이 가능하다.

In [0]:
import numpy as np

array = np.random.randint(1, 10, size=4).reshape(2, 2)
result_array = array * 10
print(array, '\n')
print(result_array)

[[9 2]
 [7 3]] 

[[90 20]
 [70 30]]


* **서로 다른 형태**의 Numpy 연산

In [0]:
import numpy as np

# 2 x 2
array1 = np.arange(4).reshape(2, 2)
# 1 x 2
array2 = np.arange(2)
array3 = array1 + array2

print(array1, '\n')
print(array2, '\n' )
print(array3, '\n')

[[0 1]
 [2 3]] 

[0 1] 

[[0 2]
 [2 4]] 



In [0]:
import numpy as np

array1 = np.arange(0, 8).reshape(2, 4)
array2 = np.arange(0, 8).reshape(2, 4)
array3 = np.concatenate([array1, array2], axis = 0)
array4 = np.arange(0, 4).reshape(4, 1)
print(array3, '\n')
print(array4, '\n')
print(array3 + array4)

[[0 1 2 3]
 [4 5 6 7]
 [0 1 2 3]
 [4 5 6 7]] 

[[0]
 [1]
 [2]
 [3]] 

[[ 0  1  2  3]
 [ 5  6  7  8]
 [ 2  3  4  5]
 [ 7  8  9 10]]


* **마스킹 연산**이 가능하다.

In [0]:
import numpy as np

#마스킹 연산 : 각 원소에 대해 체크

# Numpy 원소의 값을 조건에 따라 바꿀 때는 다음과 같이 합니다.
# 반복문을 이용할 때보다 매우 빠르게 동작합니다.
# 대체로 이미지 처리(Image Processing)에서 자주 활용됩니다.
array1 = np.arange(16).reshape(4, 4)
print(array1)

print('#########################')
array2 = array1 < 10
print(array2)

#마스킹 활용
#10보다 작은 값들을 100으로 설정
print('#########################')
array1[array2] = 100
print(array1)

[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]
 [12 13 14 15]]
#########################
[[ True  True  True  True]
 [ True  True  True  True]
 [ True  True False False]
 [False False False False]]
#########################
[[100 100 100 100]
 [100 100 100 100]
 [100 100  10  11]
 [ 12  13  14  15]]


* 다양한 **집계 함수**가 존재한다.

In [0]:
import numpy as np

#집계 함수 : 각 원소의 총합 or 평균을 빠르게 구한다.
array = np.arange(16).reshape(4, 4)

print("최대값 : ", np.max(array))
print("최소값 : ", np.min(array))
print("합계 : ", np.sum(array))
print("평균값 : ", np.mean(array))

최대값 :  15
최소값 :  0
합계 :  120
평균값 :  7.5


In [0]:
import numpy as np

#집계 함수 : 각 원소의 총합 or 평균을 빠르게 구한다.
array = np.arange(16).reshape(4, 4)
print(array)
print("모든 열에 대한 합계 : ", np.sum(array, axis = 0))

[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]
 [12 13 14 15]]
모든 열에 대한 합계 :  [24 28 32 36]
