<a href="https://colab.research.google.com/github/yih789/Data-Analysis-and-Image-Processing/blob/master/Numpy_%ED%99%9C%EC%9A%A9.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

* Numpy는 **저장 및 불러오기**가 가능하다.

In [0]:
import numpy as np

# 단일 객체 저장 및 불러오기
array = np.arange(0, 10)
np.save('saved.npy', array)

result = np.load('saved.npy')
print(result)

[0 1 2 3 4 5 6 7 8 9]


* 여러 개의 Numpy 객체를 하나의 파일에 저장하고 불러오기

In [0]:
import numpy as np

# 복수 객체 저장 및 불러오기
array1 = np.arange(0, 10)
array2 = np.arange(10, 20)
np.savez('saved.npz', array1=array1, array2=array2)

data = np.load('saved.npz')
result1 = data['array1']
result2 = data['array2']
print(result1)
print(result2)

[0 1 2 3 4 5 6 7 8 9]
[10 11 12 13 14 15 16 17 18 19]


* Numpy의 원소들은 특정 기준에 따라서 **정렬**할 수 있다.

In [0]:
import numpy as np

# 오름차순
array = np.array([5, 9, 10, 3, 1])
array.sort()
print(array)

# 내림차순
array = np.array([5, 9, 10, 3, 1])
array.sort()
print(array[::-1])

# 각 열을 기준으로 정렬
array = np.array([[5, 9, 10, 3, 1], [8, 3, 4, 2, 5]])
array.sort(axis=0)
print(array)

[ 1  3  5  9 10]
[10  9  5  3  1]
[[ 5  3  4  2  1]
 [ 8  9 10  3  5]]


* Numpy 관련 **자주 사용하는 함수들**

In [0]:
import numpy as np

# 균일한 간격으로 데이터 생성
array = np.linspace(0, 10, 5)
print (array)
print('##########################')

# 난수의 재연(실행마다 결과 동일)
# 동일한 데이터가 필요할 때 사용
np.random.seed(7)
print(np.random.randint(0, 10, (2, 3)))
print('##########################')

# Numpy 배열 객체 복사
array1 = np.arange(0, 10)
array2 = array1.copy()
print(array2)
print('##########################')

# 중복된 원소 제거
array = np.array([1, 1, 2, 3, 3, 3, 1])
print(np.unique(array))

[ 0.   2.5  5.   7.5 10. ]
##########################
[[4 9 6]
 [3 3 7]]
##########################
[0 1 2 3 4 5 6 7 8 9]
##########################
[1 2 3]
